### ISSUE TITLE
modify per worlds 

### ISSUE THREAD

**Issue by iTzAndrew33212** [nhanaz-pm-pl/CommandBlocker#2]
hey there
would it be possible to add a feature where you would be able to block commands in separate worlds, e.g. one world would be able to use a command and the other would be blocked .....

take care 
Andrew

**Comment by NhanAZ** [comment]
Will update in the next version

**Comment by iTzAndrew33212** [comment]
Fantastic news
Looking forward to test ☺️🔥🔥

**Comment by iTzAndrew33212** [comment]
Hey @NhanAZ

Any joy on making the changes 😁
Take care
Andrew

**Comment by n00bslayr94** [comment]
Agreed - I would love per world control!

**Comment by NhanAZ** [comment]
This issue has been resolved by https://github.com/nhanaz-pm-pl/CommandBlocker/commit/332e40e1601f7d8b772c7f77b6759abf38088f38

The plugin was submitted to Poggit at the time this comment was posted.

If you want to use the plugin soon, please download the plugin at:
- https://github.com/nhanaz-pm-pl/CommandBlocker
- https://poggit.pmmp.io/ci/nhanaz-pm-pl/CommandBlocker/CommandBlocker

Or wait for version 1.0.0 to be approved and released in Poggit. (https://poggit.pmmp.io/p/CommandBlocker/1.0.0)

Thanks @iTzAndrew33212 @n00bslayr94 

Enjoy!
